import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as Select from '@radix-ui/react-select';
import { ChevronDown } from 'lucide-react';
import { MethodBadge } from '../shared/Badge';
const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'];
export function UrlBar({ method, url, isLoading, onMethodChange, onUrlChange, onSend }) {
    return (_jsxs("div", { className: "flex items-center gap-2 p-3 border-b border-gray-800", children: [_jsxs(Select.Root, { value: method, onValueChange: (val) => onMethodChange(val), children: [_jsxs(Select.Trigger, { className: "flex items-center gap-1.5 bg-[#16213e] border border-gray-700 rounded px-2 py-1.5 text-sm outline-none focus:border-orange-500/50 cursor-pointer hover:border-gray-600 shrink-0", "aria-label": "HTTP Method", children: [_jsx(Select.Value, { children: _jsx(MethodBadge, { method: method }) }), _jsx(ChevronDown, { size: 12, className: "text-gray-500" })] }), _jsx(Select.Portal, { children: _jsx(Select.Content, { className: "z-50 bg-[#0d1b2a] border border-gray-700 rounded shadow-lg overflow-hidden", position: "popper", sideOffset: 4, children: _jsx(Select.Viewport, { className: "p-1", children: HTTP_METHODS.map((m) => (_jsx(Select.Item, { value: m, className: "flex items-center px-2 py-1.5 rounded cursor-pointer outline-none hover:bg-gray-700/50 data-[highlighted]:bg-gray-700/50", children: _jsx(Select.ItemText, { children: _jsx(MethodBadge, { method: m }) }) }, m))) }) }) })] }), _jsx("input", { type: "text", value: url, onChange: (e) => onUrlChange(e.target.value), onKeyDown: (e) => { if (e.key === 'Enter' && !isLoading)
                    onSend(); }, placeholder: "https://api.example.com/endpoint", className: "flex-1 bg-[#16213e] border border-gray-700 rounded px-3 py-1.5 text-base outline-none focus:border-orange-500/50 text-gray-200 placeholder-gray-600" }), _jsx("button", { onClick: onSend, disabled: isLoading, className: "px-4 py-1.5 bg-orange-500 hover:bg-orange-600 text-white text-sm font-medium rounded disabled:opacity-50 shrink-0 transition-colors", children: isLoading ? '...' : 'Send' })] }));
}
